services:
  app:
    container_name: 'app'
    build:
      context: scripts/docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: registry.buwea.pl/igorleszczynski/laravel-ci-cd:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel-ci-cd-network
    restart: always
    volumes:
      - 'laravel-ci-cd-public:/var/www/html/public'
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './scripts/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - 'laravel-ci-cd-public:/var/www/html/public:ro'
    networks:
      - laravel-ci-cd-network
    depends_on:
      - app
  mysql:
    container_name: 'mysql'
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - 'laravel-ci-cd-mysql:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    restart: always
    networks:
      - laravel-ci-cd-network
volumes:
  laravel-ci-cd-mysql:
    driver: local
  laravel-ci-cd-public:
    driver: local
networks:
  laravel-ci-cd-network:
    driver: bridge
