name: Docker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: Docker ${{ github.ref }}
  cancel-in-progress: true

env:
  package-name: laravel-ci-cd
  registry: registry.buwea.pl

jobs:
  docker-run:
    runs-on: ubuntu-latest
    name: Docker build and push

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.registry }}/${{ github.repository_owner }}/${{ env.package-name }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description="Laravel CI CD test APP"
            org.opencontainers.image.title="Laravel CI CD test APP"
            org.opencontainers.image.vendor="laravel-ci-cd"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build docker
      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.registry }}/${{ github.repository_owner }}/${{ env.package-name }}:latest
          file: scripts/docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
